### ISSUE TITLE
About adding more voicess

### ISSUE THREAD

**Issue by ShmuelRonen** [chflame163/ComfyUI_MSSpeech_TTS#3]
Hello and thank-you for this important development!!!

I am asking how to implement more voices in more languages.
There is a voicelist.txt file in the main root of the node that containe many voices, but how to implement it?

**Comment by chflame163** [comment]
Yes. voicelist.txt is contains all of the voices, but it only a text file, It doesn't put all the content in the node because it's too long too much. I want to be able to set their desired language by users, and this work is currently underway. There will be a new version update soon.

**Comment by chflame163** [comment]
> Hello and thank-you for this important development!!!
> 
> I am asking how to implement more voices in more languages. There is a voicelist.txt file in the main root of the node that containe many voices, but how to implement it?

Updated, should meet your needs.

**Comment by ShmuelRonen** [comment]
Thanks!!! it's fantstic!!!

**Comment by chflame163** [comment]
> Thanks!!! it's fantstic!!!

I'm glad you like this plugin

**Comment by ShmuelRonen** [comment]
![hebrew translate](https://github.com/chflame163/ComfyUI_MSSpeech_TTS/assets/80190186/9f54a21d-3b8d-4f09-8a8f-23bab47d65ab)
