### ISSUE TITLE
path ---bug

### ISSUE THREAD

**Issue by cardenluo** [chflame163/ComfyUI_MSSpeech_TTS#4]
![image](https://github.com/chflame163/ComfyUI_MSSpeech_TTS/assets/133877069/43e28d66-ee78-485a-8c02-c7033092857e)

**Comment by chflame163** [comment]
Perhaps you should try using the correct path name, it should not contain TWO backslashes

**Comment by cardenluo** [comment]
Sorry, I was too careless and didn't pay attention to this detail. No problem after updating the path
